version: "3"
services:
   # Database
   db:
     image: mysql/mysql-server:latest
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     ports:
       - "3306:3306"
     environment:
       MYSQL_ROOT_PASSWORD: admin
       MYSQL_DATABASE: mill
       MYSQL_USER: user
       MYSQL_PASSWORD: sathindu
     networks:
       - oilmill
   # phpmyadmin
   phpmyadmin:
     depends_on:
       - db
     image: phpmyadmin/phpmyadmin:latest
     restart: always
     ports:
       - "8080:80"
     environment:
       PMA_HOST: db
       PMA_PORT: 3306
       MYSQL_ROOT_PASSWORD: admin
     networks:
      - oilmill
networks:
  oilmill:
volumes:
  db_data:
